jobs:
  analyse_js:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - run:
          command: npm eslint
          name: Run ESLint
      - run:
          command: npm jest
          name: Jest
  checkout_code:
    executor: rn/linux_js
    steps:
      - checkout
      - persist_to_workspace:
          paths: .
          root: .
orbs:
  rn: react-native-community/react-native@6.0.1
version: 2.1
workflows:
  test:
    jobs:
      - checkout_code
      - analyse_js:
          requires:
            - checkout_code
      - rn/ios_build:
          build_configuration: Release
          device: iPhone X
          name: build_ios_release
          project_path: ios/demo.xcodeproj
          requires:
            - analyse_js
          scheme: demo
